config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path: '', path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'register'}
  resources :portfols do
    put :sort, on: :collection
  end
  get 'all_portfolio', to: 'portfols#index_all'
  
  get 'pages/home'
  get 'pages/about'
  get 'pages/contact'
  get 'pages/tech-tweet'
  resources :blogs do
    member do
      get 'toggle_status'
    end
  end
  root 'pages#home'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/shared/_alert.html.erb
<%= alert_helper %>

app/views/shared/_footer.html.erb
<footer class="footer custom-footer text-right">
  <div class="mx-5">
    <%= "#{Time.now.year}" %> JOUNGWOO BAIK <i class="far fa-copyright"></i>ALL RIGHT RESERVED
    <%= link_to 'https://github.com/woobaik' do %>
      <i class="fab fa-github-square fa-2x mx-1 site-icons"></i>
    <% end %>
    <%= link_to '<i class="fab fa-linkedin fa-2x mx-1 site-icons"></i>'.html_safe, 'https://www.linkedin.com/in/joungwoo-baik-1a3214143/'%>
  </div>
</footer>

app/views/shared/_navigation.html.erb
<nav class="navbar navbar-expand-lg custom-nav ml-5">
  <%= link_to "Joungwoo Baik", pages_home_path, class: 'navbar-brand custom-nav-brand ml-3' %>
  <button class="navbar-toggler custom-nav-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav ml-auto">
      <li class="nav-item ml-3">
        <%= link_to 'About', pages_about_path, class: 'nav-link' %>
      </li>
      <li class="nav-item ml-3">
        <%= link_to 'Contact', pages_contact_path, class: 'nav-link' %>
      </li>
      <li class="nav-item ml-3">
        <%= link_to 'Portfolio', portfols_path, class: 'nav-link' %>
      </li>
      <li class="nav-item dropdown ml-3">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Dropdown
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="#">Action</a>
          <a class="dropdown-item" href="#">Another action</a>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="#">Something else here</a>
        </div>
      </li>
    </ul>
    <span class="current-user-display"><%= "Hi, #{current_user.first_name}" if current_user %></span>
    <%= current_user_helper %>
  </div>
</nav>