config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path: '', path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'register'}
  resources :portfols do
    put :sort, on: :collection
  end
  get 'all_portfolio', to: 'portfols#index_all'
  
  get 'pages/home'
  get 'pages/about'
  get 'pages/contact'
  get 'pages/tech-tweet'
  resources :blogs do
    member do
      get 'toggle_status'
    end
  end
  root 'pages#home'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/portfol.rb
class Portfol < ApplicationRecord
  has_many :technologies
  accepts_nested_attributes_for :technologies,
    reject_if: lambda { |attributes| attributes[:name].blank?}

  include Placeholder
  validates :title, :subtitle,
            :body,
            presence: true

  after_initialize :set_defaults

  def self.by_position
    order(:position)
  end

  def set_defaults
    self.main_image ||= Placeholder.image_generator('600', '400')
    self.thumb_image ||= Placeholder.image_generator('350', '200')
  end
  
  mount_uploader :main_image, PortfolUploader
  mount_uploader :thumb_image, PortfolUploader
end

app/controllers/portfols_controller.rb
class PortfolsController < ApplicationController
    before_action :set_title
    before_action :find_portfolio, only: [:show, :edit, :update, :delete]
    before_action :authenticate_user!, only: [:new, :create, :edit, :update, :destroy]
    def index
      @portfols = Portfol.by_position
    end
    
    def index_all
      @portfols = Portfol.by_position
    end
    
    def sort
      params[:order].each do |key, value|
        Portfolio.find(value[:id]).update(position: value[:position])
      end
      
      render nothing: true
    end

    def new
      @portfol = Portfol.new
    end

    def create
      @portfol = Portfol.new(portfol_params)
      
      if @portfol.save
        flash[:success] = "Your Entry has been successfully added."
        redirect_to @portfol
      else
        flash[:error] = "There was something wrong with your entry."
        render :new
      end
    
    end

    def edit
    end

    def update
      if @portfol.update
        flash[:success] = "Your Portfolio has been successfully updated!"
        redirect_to @portfol
      else
        flash[:errror] = "There was something wrong with your entry."
        render :edit
      end
    end

    def show
    end

    def destroy
      if @portfol.destroy
        redirect_to home_path
      end

    end

  private

    def set_title
      @title = "Portfolio || Joungwoo baik"
    end

    def find_portfolio
      @portfol = Portfol.find(params[:id])
    end

    def portfol_params
      params.require(:portfol).permit(:title,
                                      :subtitle,
                                      :body,
                                      :main_image,
                                      :thumb_image,
                                      technologies_attributes: [:name, :_destroy])
    end
end

app/helpers/portfols_helper.rb
module PortfolsHelper
end

app/views/portfols/_form.html.erb
<%= form_for @portfol do |f| %>
  <p>
    <%= f.label :title %>
    <%= f.text_field :title %>
  <p>

  <p>
    <%= f.label :subtitle %>
    <%= f.text_field :subtitle %>
  </p>
  <p>
    <%= f.label :subtitle %>
    <%= f.text_field :subtitle %>
  </p>

  <p>
    <%= f.file_field :main_image %>
  </p>
  <p>
    <%= f.file_field :thumb_image %>
  </p>
  <p>
    <%= f.label :body %>
    <%= f.text_area :body %>
  </p>
  <h4>Technology Used: </h4>
    <div class="tasks">
      <%= f.fields_for :technologies do |tech_form|%>
        <%= render 'technology_fields', f: tech_form %>
      <% end %>
    </div>
    <div class="links">
      <%= link_to_add_association 'add task', f, :technologies %>
    </div>
  <%= f.submit submit %>

<% end %>

app/views/portfols/_portfol.html.erb
<div class="card" data-id="<%= portfol.id%>">
  <%= image_tag portfol.thumb_image if portfol.thumb_image %>
  <p class="card-text">
    <span>
      <%= link_to portfol.title, portfol_path(portfol) %>
    </span> <%= portfol.subtitle %>
  </p>
</div>

app/views/portfols/_technology_fields.html.erb
<div class="nested-fields">
  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>
  <div class="field">
     <%= link_to_remove_association "remove task", f %>
  </div>
</div>

app/views/portfols/edit.html.erb
<h1>Edit My Portfolio</h1>

<%= render partial: 'form', locals: {submit: "Update!"} %>

app/views/portfols/index.html.erb
<h1 class="display-2 home-title text-center">This is my <span id="my-name">Portfolio!!</span></h1>
<div class="text-right mb-4">
  <%= link_to "View All Portfolios", all_portfolio_path, class:"btn btn-info text-right"  %>
</div>
<div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
  <!-- Indicators -->
  <ol class="carousel-indicators">
    <% @portfols.each_with_index do |portfol, idx| %>
      <li data-target="carouselExampleIndicators" data-slide-to="<%= idx %>" class="<%= idx === 0 ? 'active' : 'bg'  %>"</li>
    <% end %>
  </ol>
  <!-- inner carousel -->
  <div class="carousel-inner">
    <% @portfols.each_with_index do |portfol, idx| %>
      <div class="carousel-item <%= idx.zero? ? 'active' : '' %>">
        <%= link_to portfol_path(portfol) do %>
          <%= image_tag portfol.main_image.url, class: 'd-block image-responsive', size: '1200x600' if portfol.main_image.url %>
        <% end %>
        <div class="carousel-caption d-none d-md-block">
          <h5 class="portfol-title">[ <%= portfol.title %> ]</h5>
          <p class="portfol-subtitle"> <%= portfol.subtitle %> </p>
        </div>
      </div>
    <% end %>
  </div>
  <!-- Controls -->
  <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>
<div class="text-right mt-4">
  <%= link_to "View All Portfolios", all_portfolio_path, class:"btn btn-info text-right"  %>
</div>

app/views/portfols/index_all.html.erb
<h1 class="display-2 home-title text-center">This is my <span id="my-name">Portfolio!!</span></h1>

<div class="album py-5 bg-light">
  <div class="container">
    <div class="row">
      <% @portfols.each do |portfol| %>
        <div class="col-md-4">
          <div class="card mb-4 box-shadow">
              <%= image_tag portfol.thumb_image.url, class: 'card-img-top', alt:"Portfolio image" if portfol.thumb_image.url %>
            <div class="card-body text-center">
              <p class="card-text">
                <h4 class="card-title"><%= portfol.title %></h4>
                <h6 class="card-title"> <%= portfol.subtitle %> </h6>
              </p>
              <div class="text-center">
                <%= link_to "View description", portfol_path(portfol), class: "btn btn-sm btn-outline-secondary" %>
                <%= link_to "Go Live Page", portfol.url_address, class: "btn btn-sm btn-outline-secondary" %>
              </div>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/portfols/new.html.erb
<h1>Portfolio</hi>

<%= render partial: "form", locals: {submit: 'Create new Portfolio'} %>

app/views/portfols/show.html.erb
<div class="continer portfol-show-all">
  <div class="row">
    <div class="col-md-7 text-center">
      <%= image_tag @portfol.main_image.url, class:"image-fluid", alt: 'Main', width: '80%' if @portfol.main_image.url %>
    </div>
    <div class="col-md-5 text-center">
      <h1 class="portfol-show-title"> <%= @portfol.title %></h1>
      <h3> <%= @portfol.subtitle %> </h3>
      <h6> <%= @portfol.body %> </h6>
    </div>
  </div>
</div>
<div class="text-right mt-4">
  <%= link_to "Go To Live Demo", '#', class:"btn btn-success"  %>
  <%= link_to "View All Portfolios", all_portfolio_path, class:"btn btn-info"  %>
</div>